// export const FETCH_POSTS = "FETCH_POSTS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//HOME FEED
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTION = "GET_QUESTION";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const CLEAR_HOMESTATE = "CLEAR_HOMESTATE";
export const GET_ANSWERS_FOR_QUESTIONS = "GET_ANSWERS_FOR_QUESTIONS";

export const GET_USER_DETAILS_QUESTIONS = "GET_USER_DETAILS_QUESTIONS";

export const GET_FOLLOWING_LIST = "GET_FOLLOWING_LIST";

//CONTENT
export const GET_CONTENTS = "GET_CONTENTS";
export const CLEAR_CONTENTS = "CLEAR_CONTENTS";

//Profile set
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

//Message
export const SET_MESSAGE_HISTORY = "SET_MESSAGE_HISTORY";
export const SET_RECEIVER_DATA = "SET_RECEIVER_DATA";

//DASHBOARD
export const GET_ANSWER_VIEWS = "GET_ANSWER_VIEWS";
export const GET_ANSWER_UPVOTES = "GET_ANSWER_UPVOTES";

//Follower
export const GET_FOLLOWER = "GET_FOLLOWER";

//Following
export const GET_FOLLOWING = "GET_FOLLOWING";

